#    NUMpy Universal Fucntions

In [3]:
#Compute Reciporcal of Each Array

import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

# Array Arthmetic

In [36]:

x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


There is also a unary ufunc for negation, and a ** operator for exponentiation, and a % operator for modulus

In [5]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy for example, the + operator is a wrapper for the add function


In [6]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

# Add function

In [8]:
#use Add Func
np.add(x,2)

array([2, 3, 4, 5])

# Subsctraction func

In [9]:
#Use Substraction Func
np.subtract(x,4)

array([-4, -3, -2, -1])

# Multiplication func

In [10]:
#Use Multiplication func
np.multiply(x,5)

array([ 0,  5, 10, 15])

# Divide func /

In [11]:
#Use Divide Func
np.divide(x,2)

array([0. , 0.5, 1. , 1.5])

# Power Func

In [13]:
#Use power x2,x3,x4,....
np.power(x,2)

array([0, 1, 4, 9], dtype=int32)

# Mode func

In [14]:
#Use Mode
np.mod(x,2)

array([0, 1, 0, 1], dtype=int32)

# Floor Divide //

In [44]:
np.floor_divide(x,2)

array([0, 0, 1, 1, 2], dtype=int32)

# Unray negation

In [46]:
np.negative(x)

array([ 0, -1, -2, -3, -4])

# Use Absoulte Value 
this Function Handle Complex Data ,return the Magnitude

In [16]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [17]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [18]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

# Trigonometry Functions

In [22]:
theta = np.linspace(0, np.pi, 3)

In [24]:
#theta represent angle ,by theta we can find specfic angle this method used for defining array of angle

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


# Inverse Trigonometric func

In [28]:
x = [-1, 0, 1]
#Inverse of Trigonometric Fucntion Inverse

In [26]:
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x)) # which is why values that should be zero do not always hit exactly zero

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


# EXPONENT & LOGARITHMS

In [29]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


# Inverse Exponents & Logs

In [30]:
#Inverse of This Exponent & Logarithms Fucntions
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [32]:
#For very Small Input which used in scientific Measurement
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


# Specialized Universal Func

NumPy has many more ufuncs available, including hyperbolic trig functions, bitwise arithmetic, comparison operators, conversions from radians to degrees, rounding and remainders, and much more. A look through the NumPy documentation reveals a lot of interesting functionality.

In [33]:
from scipy import special

In [34]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


# Integral of Gaussian

In [ ]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

There are many, many more ufuncs available in both NumPy and scipy.special. Because the documentation of these packages is available online, a web search along the lines of "gamma function python" will generally find the relevant information.

# Outer Product

In [37]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

The ufunc.at and ufunc.reduceat methods, which we'll explore in Fancy Indexing, are very helpful as well.

# Aggregates

For binary ufuncs, there are some interesting aggregates that can be computed directly from the object. For example, if we'd like to reduce an array with a particular operation, we can use the reduce method of any ufunc. A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

In [39]:
#For example, calling reduce on the add ufunc returns the sum of all elements in the array:

x = np.arange(1, 6)
np.add.reduce(x)

15

In [40]:
#Similarly, calling reduce on the multiply ufunc results in the product of all array elements:

np.multiply.reduce(x)

120


# Specifying Output

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a temporary array, this can be used to write computation results directly to the memory location where you'd like them to be. For all ufuncs, this can be done using the out argument of the function:

In [41]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


This can even be used with array views. For example, we can write the results of a computation to every other element of a specified array

In [42]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


but for very large arrays the memory savings from careful use of the out argument can be significant.